#name: Deploy to Hostinger

#on:
#  push:
#    branches:
#      - main  # Adjust this to match your branch

#jobs:
#  deploy:
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3

#      - name: Install dependencies
#        run: |
#          # Install any necessary dependencies here

#      - name: Push
#        uses: s0/git-publish-subdir-action@develop
#        env:
#          REPO: self
#          BRANCH: main # The branch name where you want to push the assets
#          FOLDER: main # The directory where your assets are generated
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
#          MESSAGE: "Main: ({sha}) {msg}" # The commit message
