name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Adjust this to match your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          # Install any necessary dependencies here

      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Commands to deploy your code on the Hostinger server
            # For example, you might use SCP or SFTP to copy files
            # to the server and run any deployment scripts.
